language: objective-c

osx_image: xcode7.2

before_install:
   - rvm install 2.2.2
   - sudo gem install cocoapods -v '1.0.1'

script: 
   xctool -workspace PaginationCoreDataExample.xcworkspace -scheme PaginationCoreDataExample build -sdk iphonesimulator
