language: objective-c

osx_image: xcode7.2

before_install:
   - rvm use system
   - gem install cocoapods -v '0.39.0'  
   - pod repo update

script: 
   xctool -workspace PaginationCoreDataExample.xcworkspace -scheme PaginationCoreDataExample build -sdk iphonesimulator
